### ISSUE TITLE
Is there a way to count how many people have been detected in faceDetect.cpp

### ISSUE THREAD

**Issue by chfakht** [Itseez/opencv#5252]
I am running the code faceDetect.cpp , i need to count how many people are beign detected , i can detect how many people are in in the same frame by incrementing a variable for each face detected but in the case for example if the person appear , disapear and re-appear  i couldn't find a way to count it as just one person 
any hints ?
poke again :  @avdmitry and @vpisarev  :vertical_traffic_light: please stop here :fast_forward:

**Comment by StevenPuttemans** [comment]
You should direct questions like this to the OpenCV Q&A forum on https://answers.opencv.org/questions/ where a lot of people will help you way sooner then here. Normally if you apply face detection, then the size of the returned objects vector is the amount of people detected. For tracking a person over time you will need a tracker that remembers positions and gets updated by detections, like the Kalman filter.

**Comment by chfakht** [comment]
yes i'm not interrested in the size of the returned objects because ir can give more than 10 persons for only one face beign detected so it's not the way to do it ..... ++ i'm very interrested to the second solution using kalman filter for tracking a person over time , it's a lot complex , do you have any ressources on that or implementation .
thanks :neckbeard:

**Comment by StevenPuttemans** [comment]
"yes i'm not interrested in the size of the returned objects because ir can give more than 10 persons for only one face beign detected so it's not the way to do it ....."

I do not agree, if you built a robust face detector, then it will not yield 10 detections for each individual... Just look for good parameters and apply some post filtering on detections to know if this is actually a face image or not.

As to the tracking stuff, look at this Kalman filter example: http://opencvexamples.blogspot.com/2014/01/kalman-filter-implementation-tracking.html

**Comment by chfakht** [comment]
yes you right i must try to filter out the frames maybe using kalman filter or just a simple filter , thanks you

**Comment by StevenPuttemans** [comment]
Then I suggest closing this topic down :)

**Comment by chfakht** [comment]
Ook :100:
