### ISSUE TITLE
OpenCV 3.0 links to both Debug and Release external ZLIB library on Windows

### ISSUE THREAD

**Issue by willyd** [Itseez/opencv#5264]
Hi, I am trying to build OpenCV on Windows and using my own ZLIB library with my own FindZLIB module. My FindZLIB module does:
```CMake
set(ZLIB_LIBRARIES optimized ${ZLIB_LIBRARY} debug ${ZLIB_LIBRARY_DEBUG})
```
however line 469 in [OpenCVModule.cmake](https://github.com/Itseez/opencv/blob/3.0.0/cmake/OpenCVModule.cmake) messes up the libraries order. This makes opencv_core depend on both the debug and release libraries of ZLIB and any consuming project that uses OpenCV's exported targets link to both release and debug versions of ZLIB.

I thought of three possible solutions:

* Append `${ZLIB_LIBRARIES}` to the `extra_libs` when `BUILD_ZLIB=OFF` instead of passing it to ocv_add_module.
* Preprocess the `OPENCV_MODULE_${m}_DEPS_EXT` list to merge together the keyword and the library so that a list like:
```CMake
debug;c:/path/to/zlibd.lib;optimized;c:/path/to/zlib.lib
```
becomes
```CMake
"debug c:/path/to/zlibd.lib";"optimized c:/path/to/zlib.lib"
```
and then split the merged list elements after.
* Or, after `find_package(ZLIB)` succeeds create an imported target named `OpenCV::ZLIB` from the debug and optimized libraries and use `set(ZLIB_LIBRARIES OpenCV::ZLIB)`. And then extract the proper Release and Debug libs before linking `if(${ZLIB_LIBRARIES} EQUAL OpenCV::ZLIB)`.

All solutions seem a bit hackish. Is there a proper way of handling this use case?

**Comment by alalek** [comment]
`optimized` and `debug` CMake features is not recommended to use with OpenCV. There are many issues and you catch one of them.
Instead of this, try to use `IMPORTED` targets and pass to OpenCV target name only. Configurations for IMPORTED targets can be generated by CMake semi-automatically if you have CMake projects for your library (via `export` command: http://www.cmake.org/cmake/help/v2.8.11/cmake.html#command:export )
Manual creation of `IMPORTED` target is here: https://github.com/Itseez/opencv/blob/faa668437357f6433bc1c01508b9eec62827d130/cmake/OpenCVFindIPP.cmake#L143-L147
To split debug and release configurations you can try to use these properties: 
- `IMPORTED_LOCATION_DEBUG`
- `IMPORTED_LOCATION_RELEASE`

**Comment by willyd** [comment]
@alalek Let me test this and get back to you.

**Comment by willyd** [comment]
After reviewing the changes I would say that this works only partially. With the code above OpenCV should correctly link to the release and debug libraries. But it will also export targets with a dependency on imported target `z` when building static libraries. Thus I will need to somehow define this imported library in my cmake project. 

Maybe the OpenCVConfig.cmake could take care of resolving this dependency via [find_dependency](http://www.cmake.org/cmake/help/v3.3/module/CMakeFindDependencyMacro.html)? 

Otherwise, when opencv_core links to ZLIB maybe it could call [cmake_expand_imported_targets](http://www.cmake.org/cmake/help/v3.3/module/CMakeExpandImportedTargets.html) so that the references are absolute paths in the OpenCVConfig.cmake?

**Comment by alalek** [comment]
Your ZLIB is static (.lib only) or shared library (.dll+.lib)?

**Comment by willyd** [comment]
static
