### ISSUE TITLE
"Using OpenCV Java with Eclipse" out of date

### ISSUE THREAD

**Issue by i-make-robots** [Itseez/opencv#5380]
http://docs.opencv.org/3.0-beta/doc/tutorials/introduction/java_eclipse/java_eclipse.html

"Launch Eclipse and select Window –> Preferences from the menu."  
In OSX this is in Eclipse > Preferences.

"Browse through C:\OpenCV-2.4.6\build\java\ and select opencv-246.jar. "
OpenCV-3.0.0 has no build folder.

Stuck here, can't validate the rest of the tutorial.

**Comment by mshabunin** [comment]
The tutorial is intended for Windows developers and uses distributed binary package for windows. Since there is no official binary package for OSX, you should build it from sources yourself.

The build steps are similar to those described in [Linux tutorial](http://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html#gsc.tab=0) section "Building OpenCV from Source Using CMake". You will need cmake, clang and Java SDK installed as prerequisites.

You can also refer to OpenCV buildbot logs for some details: http://pullrequest.opencv.org/buildbot/builders/precommit_macosx/builds/4046
Note the `--     Java wrappers:               YES` line in the cmake output, it means the jar file will be built.
