### ISSUE TITLE
Cloning the OpenCV git repository locally is extremely slow

### ISSUE THREAD

**Issue by StevenPuttemans** [Itseez/opencv#5416]
Since a month of 2, cloning the repository locally on a machine for development is extremely slow, running up to 15kb/sec... while it was several MB/sec before. Anyone has a clue what could be the reason for this?

**Comment by alalek** [comment]
What is "locally" mean exactly?

There are some general notes:
1) Use `-s` flag for local clone (remote is file system on your machine). This will share internal .git objects and will not copy them.
2) Use --depth for remote clone (without full history, and without most part of tags):
```
git clone --depth=10 https://github.com/Itseez/opencv.git
git clone --depth=10 -b 2.4 https://github.com/Itseez/opencv.git
```
This will not increase "speed", but amount of downloaded data is reduced significantly.
It is possible to download all history later (via `git fetch`).
3) Use --depth for remote fetch, but be careful (git rebase may not work in some cases):
```
git fetch --depth=100 upstream
```

**Comment by StevenPuttemans** [comment]
Well locally means that I am performing the following command `git clone https://github.com/Itseez/opencv.git opencv` on a folder here on my workstation and then let it run freely. I do want a complete new clone on this machine, like in the case that there is not yet a clone available for a local copy.

I did not know the depth parameter. Will try that and see how it goes!

**Comment by Dikay900** [comment]
Sometimes the github server are a bit slow cloning a repo. I do not think that anyone here can solve this issue if this occurs.

The --depth parameter will help there definitely because you won't download currently deleted files.

But there are some other faster methods you can also use.
1. you could access another pc in your intranet if it is setup to let you connect and have a copy of the opencv repo.
2. If you can access an usb device u rather should copy the .git folder in the opencv folder of another pc where you already worked on.
use
`git gc`
to minimize the files need to be copied and after copying the .git folder into another folder on your workstation you can simply use.
`git reset --hard`
And your working directory is ready, where you only need to update to the latest rev if needed.

**Comment by StevenPuttemans** [comment]
Copying a version of OpenCV does not seem to work, because then the MD5 hash for downloading IPP is not correct anymore. Seems to be system specific.

**Comment by Dikay900** [comment]
Copying the .git folder will only copy git relevant files, while copying the whole folder will be problematic.
Resetting it will create a fresh repo just like you would download with git clone, if you only copy the .git folder.

**Comment by StevenPuttemans** [comment]
:+1:
