### ISSUE TITLE
Question about HAARs and LBP training

### ISSUE THREAD

**Issue by gplumb** [Itseez/opencv#5428]
Hi

I was wondering what source data was used to train the LBP/HAARS xml in the project?  Did the source data/vectors differ between the cascades?

The reason I'm asking is I'd like to use the same data/vectors from the HAARs training to generate LBP equivalents...

Thanks!
G

**Comment by StevenPuttemans** [comment]
Yes both models were trained on the same data, since they were used to prove that with only a slightly lesser accuracy, training time is reduced drastically. The *.vec file that was used to train both cascades can be found here: https://github.com/Itseez/opencv/blob/master/data/vec_files/trainingfaces_24-24.vec

However, there is no details, except from the ones stored in the model, on which parameters were used to train the original models, so it would be best to select your set of parameters and use them for both models, to end up with a fair comparison. 

In the future, requests like this can be directed to http://answers.opencv.org/questions, so that we can avoid clugging up the issues pages. Therefore I would like to request you to close this one down. Thank you in advance.

**Comment by gplumb** [comment]
Thank you for getting back to me (and my apologies for posting in the wrong place!).

For anyone else curious about training your own detectors (the reason behind my original question), I have found this youtube video particularly useful in getting started: http://goo.gl/SYXz2s

G

**Comment by StevenPuttemans** [comment]
:+1: thank you!
