### ISSUE TITLE
no error message when opencv_ffmpeg.dll is not found

### ISSUE THREAD

**Issue by LaurentBerger** [Itseez/opencv#5694]
Hi,
At line https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg.cpp#L105 opencv try to download opencv_ffmpeg.dll. If this dll is not found there is no error message sent to user. 
I think that changed 0 in 1 at line https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg.cpp#L129 solve this problem (if it is a problem)

**Comment by alalek** [comment]
1) not download, just try load
2) It is not a bug, it is done by design to prevent annoying messages. There are a lot of licensing and patent issues, so ffmpeg is an optional feature. ffmpeg can be disabled by "opencv_ffmpeg*.dll" files removal from the distribution.
3) I agree that current video/camera access implementations are very hard to "debug". Some logging is required here, but it is a new feature actually.
