### ISSUE TITLE
Regression in cap_gstreamer when viewing rtsp streams.

### ISSUE THREAD

**Issue by dtmoodie** [Itseez/opencv#5918]
At line 805 in cap_gstreamer.cpp the if(file) has been removed, this breaks accessing rtsp streams from axis surveillance cameras.
My pipeline string is:
rtspsrc location=rtsp://login:pass@192.168.1.51:554/axis-media/media.amp ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! video/x-raw, width=1920, height=1080 ! appsink

Adding if(file) back in at that line fixes the problem.  Not sure why it was removed.

**Comment by alalek** [comment]
Related: #5202
Did you try to comment `stopPipeline();` line?

cc @ilya-lavrenov

**Comment by dtmoodie** [comment]
That looks to fix it as well.

**Comment by rafosierra** [comment]
Hi.

Recently upgraded to version 3.1 from 3.0 and hit this issue. I use a pipeline to open an USB camera like this: `"v4l2src ! video/x-raw ! decodebin ! videoconvert ! appsink"`
I get this error: `OpenCV Error: Unspecified error (GStreamer: unable to start pipeline) in icvStartPipeline ...`

Tried both suggestions above: adding the `if (file)` condition in front of the block at line 805, and removing the `stopPipeline();` line; both worked.

Being that this issue is already tagged as **bug** and has an **assignee**, I'd like to know the status of it: Should I create a pull request with a patch or should I just wait for it to be fixed?

Thanks.
