### ISSUE TITLE
Using ORB or BRIEF features with FlannBasedMatcher causes exception

### ISSUE THREAD

**Issue by ejoebstl** [Itseez/opencv#5937]
Supplying ORB or BRIEF features to a FlannBasedMatcher causes an exception:

```
opencv/modules/flann/src/miniflann.cpp:315: error (-210): type=0
```

It seems like flann does not accept the ```8UC1```descriptor extracted by ORB or BRIEF. 

Since this is imporant for my project, I'll continue to investigate. Any hints would be highly appreciated!

**Comment by cbalint13** [comment]
@ejoebstl ,
* Can post a simple testcase ?

**Comment by ejoebstl** [comment]
Of course!

```
#include <opencv2/opencv.hpp>
#include <opencv2/features2d.hpp>
#include <opencv2/xfeatures2d.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/stitching/detail/matchers.hpp>

using namespace cv;
using namespace cv::detail;
using namespace cv::xfeatures2d;
using namespace std; 

int main(int argc, char **argv) {

    // Does not work. 
    typedef FastFeatureDetector Detector;
    typedef BriefDescriptorExtractor Extractor;
    
    // Does work. 
    // typedef SURF Detector;
    // typedef SURF Extractor;

    assert(argc == 3);

    Mat a = imread(string(argv[1]));
    Mat b = imread(string(argv[2]));

    Ptr<Detector> detector = Detector::create();

    ImageFeatures aFeatures, bFeatures;

    detector->detect(a, aFeatures.keypoints);
    detector->detect(b, bFeatures.keypoints);

    Ptr<Extractor> extractor = Extractor::create();

    extractor->compute(a, aFeatures.keypoints, aFeatures.descriptors);
    extractor->compute(b, bFeatures.keypoints, bFeatures.descriptors);

    FlannBasedMatcher matcher;
    vector<vector<DMatch>> matches;

    matcher.knnMatch(aFeatures.descriptors, bFeatures.descriptors, matches, 2);

    if(matches.size() > 0)
        cout << "Woop woop it worked. :)" << endl;

    return 0;
}
```

Please pass paths to two images as parameters to the program. 
It can be observed that the code works with SURF, but crashes with FAST + BRIEF during FLANN matching. 

The exact error is:

```
OpenCV Error: Unsupported format or combination of formats (type=0
) in buildIndex_, file /.../opencv/modules/flann/src/miniflann.cpp, line 315
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /.../opencv/modules/flann/src/miniflann.cpp:315: error: (-210) type=0
 in function buildIndex_

fish: 'build/src/minimal-feature-tes...' terminated by signal SIGABRT (Abort)
```

**Comment by ejoebstl** [comment]
Okay, it works if the following constructor call is used to create the FlannBasedMatcher: 

```
FlannBasedMatcher matcher(new flann::LshIndexParams(20, 10, 2));
```

I'll still leave this issue open - please provide a clearer error message in this case. 

An explanation can be found [here](http://answers.opencv.org/question/547/using-flann-with-binary-descriptors-brieforb/).

**Comment by cbalint13** [comment]
@ejoebstl ,

I believe it is not a bug. 

* BRIEF & ORB are hamming class descriptors. By default matcher creates L2 euclid KDTreeIndexParams(). Indeed, by specifing Lsh() indexer/hasher works because is hamming class. I believe your solution is to _always_ specifie what hasher/matcher you want exactly. 

* Hint: You can use extractor->descriptorType() and extractor->defaultNorm() to query what class of descriptor is and make inplace decision what matcher will want to use.

(1) You got the error becouse you tried hamming type over euclid type:
"Unsupported format or combination of formats (type=0)", where type=0 is CV_8U (as hamming descriptors outputs like BRIEF, ORB, FREAK, AKAZE etc).

(2) As another odd example: e.g i want to run Lsh() over SURF i got the reverse error:
" Unsupported format or combination of formats (type=5", where type=5 is CV_32F (as any euclid descriptors outputs).

Obviously, OpenCV flann module cannot decide what type you intend to use but can warn you if use the odd combination. Perhaps we can teach OpenCV to be more explicit in its errors with simple clear and comprehensible texts instead of "type=0", but this is another issue.

**Comment by ejoebstl** [comment]
Thank you a lot for the explanation.

Explicit errors - that sounds awesome!
