### ISSUE TITLE
Android tutorial 4 missing in 3.1 release

### ISSUE THREAD

**Issue by PhilLab** [Itseez/opencv#6138]
The [tutorial-4-opencl](https://github.com/Itseez/opencv/tree/master/samples/android/tutorial-4-opencl) is missing in the official android release of [3.1.](https://github.com/Itseez/opencv/releases/tag/3.1.0) but it is mentioned in the [Changelog](https://github.com/Itseez/opencv/wiki/ChangeLog):

 > Support for Camera2 API in Android 5+. See opencv/samples/android/tutorial-4-opencl [...]

I was especially interested in the prebuilt apk to quickly test the performance improvement myself, but both source folder and apk are missing

**Comment by alalek** [comment]
There is no chance to safely redistribute current version of this app via common OpenCV package, because there are lot of very specific requirements (like libOpenCL.so from the target device, which is usually not portable between vendors).

http://docs.opencv.org/master/d7/dbd/tutorial_android_ocl_intro.html

**Comment by PhilLab** [comment]
Okay, our other discussion #5438 seems to be related and I will close both issues because of their unsolvability. The change log was overly optimistic regarding this matter :sweat_smile:
