### ISSUE TITLE
What's a good way to pass an array of cv::GpuMat to a cuda kernel?

### ISSUE THREAD

**Issue by liquidmetal** [Itseez/opencv#6197]
I'm trying to pass an array of cv::GpuMat (a bunch of masks) to a cuda kernel. Is there a way to do
this? I've posted the question on the OpenCV q&a site as well.

```
__global__ void somename(cv::cuda::PtrStepSz<float> *array_of_images) {
    ...
    }
...
int main(...) {
    cv::cuda::GpuMat *mats = new cv::cuda::GpuMat[180]();
    // Initialize eachof the mats
    somename<<<...>>>(mats);           // Doesn't work
}
```

The compile time error I'm seeing is:
```
filename.cu(89): error: argument of type "cv::cuda::GpuMat ​*" is incompatible with parameter of type "cv::cuda::PtrStepSz<float> *"
```

http://answers.opencv.org/question/89050/passing-an-array-of-cvgpumat-to-a-cuda-kernel/

**Comment by alalek** [comment]
This place is bad for questions. Keep track of http://answers.opencv.org

**Comment by liquidmetal** [comment]
I suspect this might be a limitation of OpenCV at the moment. If so, I was hoping this would help guide discussion on this topic and future implementation.

**Comment by sarthakahuja11** [comment]
@liquidmetal I am working on a project and facing a similiar problem. I am not sure if NVCC will compile this or not. Please let me know if it possible and how?
Or if there is an possible alternative to it?

**Comment by jet47** [comment]
Use https://github.com/opencv/opencv/blob/master/modules/cudafeatures2d/src/brute_force_matcher.cpp#L130 example.

**Comment by sarthakahuja11** [comment]
@jet47 Thanks a lot for your help!

Actually the problem is I am recieving a Mat Image in a function and i want it to split it into 3 channels, hence I am not sure if I pass a Mat image function in the cpp file, then in the .cu file converting into a unsigned char pointer than in the final kernel making it a PtrStepSz<uchar3>

These are my function calls:
Mat imghsv,dstimg,dstimg1,dstimg2;
void gpu_inRange(imghsv, dstimg,dstimg1, dstimg2);
.
.
..

extern "C" void gpu_inRange(unsigned char *h_imghsv, unsigned char *dstimg, unsigned char *dstimg1, unsigned char *dstimg2)
.
..
..

 gpu_inRange_kernel<<<gridSize, blockSize>>>(d_imghsv,dstimg,dstimg1,dstimg2);
.
.
.
.
.
..
void gpu_inRange_kernel(const PtrStepSz<uchar3> imghsv,PtrStepSzb dstimg, PtrStepSzb dstimg1, PtrStepSzb dstimg2)
.
...
..
Right now I'm pretty uncertain if this will work or not. As I guess there are too many conflicting data types plus I have'nt used these before.
I think if change the unsigned char* into a GpuMat , then will it work?
As it is mentioned in the Documentation " The GpuMat class is convertible to cuda::PtrStepSz and cuda::PtrStep so it can be passed directly to the kernel"

So is the following declaration better?

extern "C" void gpu_inRange(cv::cuda::GpuMat h_imghsv, cv::cuda::GpuMat dstimg, cv::cuda::GpuMat dstimg1, cv::cuda::GpuMat dstimg2)


I started learning CUDA few months back and still I am figuring few things. It would be really great if you could help me with this.
Thanks a ton!
:)
