### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by arpit15** [Itseez/opencv#6280]
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04)  

I am facing following problem in building the example file ~/opencv/samples/cpp/tutorial_code/features2D/AKAZE_match.cpp

Linking CXX executable ../../bin/cpp-tutorial-planar_tracking
CMakeFiles/tutorial_planar_tracking.dir/tutorial_code/features2D/AKAZE_tracking/planar_tracking.cpp.o: In function `main':
planar_tracking.cpp:(.text.startup.main+0x670): undefined reference to `cv::selectROI(cv::String const&, cv::Mat, bool, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cpp-tutorial-planar_tracking] Error 1
make[1]: *** [samples/cpp/CMakeFiles/tutorial_planar_tracking.dir/all] Error 2
make: *** [all] Error 2

Compile instructions used
```
mkdir build && cd build
ccmake ..
make -j4
```

The compilation was successful if I commented out the line 173-180 in ~/opencv/samples/cpp/tutorial_code/features2D/AKAZE_tracking/planar_tracking.cpp.

However make test has failed. Kindly provide the suggestion why this might be happening?
Any help is appreciated.

**Comment by StevenPuttemans** [comment]
Problems like this are better added at [the Q&A forum](http://answers.opencv.org/questions) where you will get an answer way sooner!

First of all, did you build OpenCV with the opencv_contrib modules? Because tracking API has moved there. If you did not add this module while building OpenCV then the sample will not work, because the tracking API will not be built into your cv namespace.

**Comment by berak** [comment]
also see #6209 .

and i disagree, a sample in main opencv, demonstrating homography with akaze/orb, should not rely on the tracking module from opencv_contrib

**Comment by StevenPuttemans** [comment]
:+1:  i agree @berak  :)
