### ISSUE TITLE
old (OpenCV2) SVM classifier won't load properly

### ISSUE THREAD

**Issue by mixmixmix** [Itseez/opencv#6301]
Hello:

Loading classifiers trained in opencv3 into an old opencv2 project is possible but requires a few changes to the file. Is there a good reason for dropping compatibility? I can imagine quite a few people trying to use pre-trained classifiers in new projects.

Differences: 
- was **svm_type**, is  **svmType**
- was tag `<my_svm type_id="opencv-ml-svm">`, now not there anymore
- matrix **class_labels** is transposed
- tag `<var_all>` is missing

### OpenCV2 SVM file:
```
<?xml version="1.0"?>
<opencv_storage>
<my_svm type_id="opencv-ml-svm">
<svm_type>C_SVC</svm_type>
<kernel>
  <type>RBF</type>
  <gamma>12.</gamma></kernel>
<C>8.</C>
<term_criteria><epsilon>1.1920928955078125e-07</epsilon>
  <iterations>1000</iterations></term_criteria>
  <var_all>2000</var_all>
<var_count>2000</var_count>
<class_count>3</class_count>
<class_labels type_id="opencv-matrix">
  <rows>1</rows>
  <cols>3</cols>
  <dt>i</dt>
  <data>
    0 1 2</data></class_labels>
<sv_total>2441</sv_total>
<support_vectors>
  <_>
...
</index></_></decision_functions></my_svm>
</opencv_storage>
```

### Current, OpenCV3 form of SVM formatting:
```
<?xml version="1.0"?>
<opencv_storage>
<svmType>C_SVC</svmType>
<kernel>
  <type>RBF</type>
  <gamma>12.</gamma></kernel>
<C>8.</C>
<term_criteria><epsilon>1.1920928955078125e-07</epsilon>
  <iterations>1000</iterations></term_criteria>
<var_count>2000</var_count>
<class_count>3</class_count>
<class_labels type_id="opencv-matrix">
  <rows>3</rows>
  <cols>1</cols>
  <dt>i</dt>
  <data>
    0 1 2</data></class_labels>
<sv_total>2441</sv_total>
<support_vectors>
  <_>
...
</index></_></decision_functions>
</opencv_storage>
```

**Comment by mshabunin** [comment]
@mixmixmix , _ml_ module has been rewritten in 3.0 and storage format has been changed. But old models (from 2.4) should be supported in current master branch version. Please, take a look at [this](https://github.com/Itseez/opencv/blob/f3127521f3fbbc1b2db18f5ae333cafb5861b25a/modules/ml/src/svm.cpp#L2113-L2160) loading code and [this](https://github.com/Itseez/opencv/blob/f3127521f3fbbc1b2db18f5ae333cafb5861b25a/modules/ml/test/test_save_load.cpp#L185-L224) compatibility test (and [data](https://github.com/Itseez/opencv_extra/tree/master/testdata/ml/legacy)).

Models from 3.x can not be loaded in 2.4, because we tried to keep backward compatibility, but not forward. You can modify version 2.4 to support new models, but we recommend to use 3.x version instead.

Also please note that due to changes in algorithm implementations some loaded models can produce different results.

**Comment by mixmixmix** [comment]
@mshabunin Thanks for explanation. Backward compatibility doesn't seem to work in my case neither. I had to edit the same fields as when moving from 3 to 2, but this is I guess different issue to report.
