### ISSUE TITLE
no member named 'GetCocoaServer' 

### ISSUE THREAD

**Issue by hyuce** [Itseez/opencv#6315]
Hi;
When I compile openCV 3 (HEAD) version, it has been broken compiling.
I can use PCL and VTK normaly.
How can I solve this problem.

```
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:284:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:285:20: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        if (!this->GetCocoaServer ())
             ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:288:19: error: no member named 'SetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
            this->SetCocoaServer (reinterpret_cast<void*> (server));
            ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:300:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
4 errors generated.
make[2]: *** [modules/viz/CMakeFiles/opencv_viz.dir/src/vtk/vtkCocoaInteractorFix.mm.o] Error 1
make[1]: *** [modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by sunstarchan** [comment]
I meet this too, how's the progress?

**Comment by chengguo1987** [comment]
I had the same problem with VTK 7.0.0 and OpenCV 3
After reading multiple posts online I figured out the reason.

Since VTK version 6.2, the GetCocoaServer() and SetCocoaServer() function calls were moved from vtkRenderWindowInteractor to vtkRenderWindow.

The opencv-3.1.0/modules/viz/src/vtk/vtkCocoaInteractorFix.mm was designed to solve this Issue, so it will fix potential problems for VTK version >= 6.2

The original vtkCocoaInteractorFix.mm code uses a one-line version detection macro, i.e.

`#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION  >=2` 

If we use VTK 7.0.0, although it is a newer version, the minor version is less than two, so the vtkCocoaInteractorFix.mm will handle this as older VTK versions and that causes the problem.

So to fix this we just need to add the version number 7 to the line.

`#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION  >=2 || VTK_MAJOR_VERSION >=7`

Then the opencv3 can be built successfully.

**Comment by DelightRun** [comment]
Thank you very much for solving the problem. @chengguo1987 
Should we create a PR about this?

**Comment by chengguo1987** [comment]
@DelightRun I already made a pull request on the opencv github site.

**Comment by heinemml** [comment]
Shouldn't this patch also be applied to the 2.4 branch? Same problem is happening there.
