### ISSUE TITLE
Threshold function lacks support for CV_64F

### ISSUE THREAD

**Issue by arjo129** [Itseez/opencv#6519]
### Please state the information for your system
- OpenCV version:  3.0.0
- Host OS: Mac OS X 10.11.3 

### In which part of the OpenCV library you got the issue?
Examples:
- imgproc

### Expected behaviour
I want to perform a simple threshold to zero of a CV_64F `cv::Mat` using opencv's builtin threshold function.
### Actual behaviour
Opencv's threshold does not support CV_64F.

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
    Mat c(1,1,CV_64F,Scalar(1));
    threshold(c, c, 0, 255, THRESH_TOZERO);
    return 0;
}
```

**Comment by zhexuany** [comment]
I reproduce the bug here. The error information is the following:
`OpenCV Error: Unsupported format or combination of formats () in threshold, file /Users/zhexuany/repo/opencv/modules/imgproc/src/thresh.cpp, line 1273
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/zhexuany/repo/opencv/modules/imgproc/src/thresh.cpp:1273: error: (-210)  in function threshold`
